[project]
name = "llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beartype>=0.22.9",
    "einops>=0.8.2",
    "jaxtyping>=0.3.11",
    "numpy>=2.5.2",
    "torch>=2.13.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
